### PR TITLE
Rename `boost::swap` to `boost::core::invoke_swap`, deprecate `boost::swap`

### PR DESCRIPTION
**Pull request by Lastique**
The rename allows to avoid forming an infinite recursion in compile time (because of `noexcept` specification that needs to resolve the unqualified call to `swap`) or run time (in case if the `boost::swap` function is the only one suitable for the passed arguments).

To avoid the compile-time recursion, removed `noexcept` specification from `boost::swap`. The specification is still present in `boost::core::invoke_swap`.

Deprecated `boost::swap` and associated headers. `boost::core::invoke_swap` is defined in a new `boost/core/invoke_swap.hpp` header.

Updated docs and tests. Removed tests that check inclusion of deprecated headers.

Fixes https://github.com/boostorg/core/issues/148.

### CODE REVIEW

**Comment by pdimov** [comment]
This looks good to me. @glenfe?

**Comment by Lastique** [comment]
Also, do we want this to be part of 1.83? I did not create any PRs updating other libraries to switch over to `invoke_swap`.

**Comment by pdimov** [comment]
It's probably too late for 1.83.

**Comment by Lastique** [comment]
> It's probably too late for 1.83.

Yeah, I thought so too. I'll merge this after the release then. 1.83 will be released as currently is.

**Comment by glenfe** [comment]
Looks good to me.

We might want to delay 1.83 for other reasons (Context submodule being disconnected from master HEAD has resulted in other issues) so I want to think about getting this in. Versus shipping 1.83 with broken Context etc.

**Pull request merged**
