### PR TITLE
bit.hpp: Use C++17 if constexpr where possible

### PR DESCRIPTION
**Pull request by Lastique**

### CODE REVIEW

**Comment by Lastique** [comment]
@pdimov Ping?

**Comment by pdimov** [comment]
I'm not sure why would I want this change. It makes the source uglier and does effectively nothing else. At the same time, I don't have any good arguments against, either.

**Comment by Lastique** [comment]
It reduces the amount of code to compile. In each function, only one branch is enabled for a given call, the rest are just wasting compile time on overload resolution and DCE. `if constexpr` should allow to discard these branches earlier.

**Comment by pdimov** [comment]
All right, let's give it a go.

**Pull request merged**
