### PR TITLE
Update addressof.hpp

### PR DESCRIPTION
**Pull request by akumta**
To update ticket# 10311

### CODE REVIEW

**Comment by pdimov** [comment]
Wouldn't it be better if we use BOOST_WORKAROUND for consistency?

**Comment by Lastique** [comment]
Frankly, I always found BOOST_WORKAROUND/BOOST_TESTED_AT confusing.

**Comment by pdimov** [comment]
In this case it would not use BOOST_TESTED_AT. `defined(__SUNPRO_CC) && BOOST_WORKAROUND(__SUNPRO_CC, <= 0x5120)`.

The idea of BOOST_WORKAROUND is both to mark something as a workaround and to make it possible for all workarounds to be turned off (so that the supposedly conforming code is chosen.)

In principle, the original should already have used BOOST_WORKAROUND, this time with BOOST_TESTED_AT, like `defined(__SUNPRO_CC) && BOOST_WORKAROUND(__SUNPRO_CC, BOOST_TESTED_AT( 0x590))`. This says that all known versions need the workaround and the latest version tested was 5.9. When 5.13 is then discovered to no longer need the workaround, we change BOOST_TESTED_AT with the appropriate <= test.

**Comment by Lastique** [comment]
Thanks for the explanation. The problem is when I read the code I don't immediately know what `BOOST_WORKAROUND(__SUNPRO_CC, BOOST_TESTED_AT(0x590))` means. Is this condition true only for 0x590 version? What about other versions, are they not tested with the workaround? What in fact that means is 'always return `true` unless `BOOST_DETECT_OUTDATED_WORKAROUNDS` is defined'. So the version number doesn't really matter. This gives me a stutter.

The sole `BOOST_WORKAROUND` is better in this respect because I can at least see the condition.

**Comment by pdimov** [comment]
Yes, you have to know what it means. But once you know, it's not really possible to misinterpret.

**Pull request merged**
