### PR TITLE
add boost_core.natvis and interface project sources

### PR DESCRIPTION
**Pull request by vinniefalco**
moved the file to extra/ and tidied up the CML

### CODE REVIEW

**Comment by glenfe** [comment]
Looks OK to me.

**Comment by Lastique** [comment]
I'm ok too.

**Comment by pdimov** [comment]
I'll merge this - eventually - but I want to think about the CML part a bit first.

**Comment by vinniefalco** [comment]
Any thoughts on this?

**Comment by pdimov** [comment]
I'm sitting on all these because while the .natvis files can be added immediately, I don't want to make the CMakeLists.txt changes in this manner because it will make them not match the `boostdep --cmake` output so they'll need to be maintained by hand from that point on, and I'd like to avoid that.

I was going to pick and merge the .natvis files by hand but I'm busy with other things now.

**Comment by vinniefalco** [comment]
Can boostdep integrate .natvis files into the CML if it sees them?

**Pull request merged**
