### PR TITLE
Fix error: 'ref_empty' is not a member

### PR DESCRIPTION
**Pull request by denzor200**

### CODE REVIEW

**Comment by pdimov** [comment]
This doesn't look like the right fix. But in either case, please first give an example that fails.

**Comment by denzor200** [comment]
> Look at the CI fails in develop

https://github.com/boostorg/pfr/actions/runs/3857066454/jobs/6574035091
It also breaks Boost PFR's CI and stops my work on it.

**Comment by pdimov** [comment]
Oh, @Lastique has been doing things. Andrey, please do things on a branch first, before merging to develop.

**Comment by Lastique** [comment]
Oops, sorry for this. I thought I ran the tests locally, but apparently I did so on an intermediate version of the code. Should be fixed now.

**Comment by Lastique** [comment]
> Andrey, please do things on a branch first, before merging to develop.

Ok. Sorry again.

**Pull request closed without merging**
